resources:
- name: repo
  type: git
  source:
    uri: https://github.com/corelogic/vault-test-pipeline.git
    branch: master
    username: clbuildteam
    password: ((git.token))

jobs:
- name: hello-world
  public: false
  plan:
  - get: repo
  - task: say-hello
    file: repo/tasks/task.yml
    params:
      VAULT_SECRET: {{vault-secret}}
      FOO: {{foovar}}
