resources:
- name: repo
  type: git
  source:
    uri: ((github-uri))
    branch: ((github-branch))
    username: ((github-username))
    password: ((github-token))

jobs:
- name: hello-world
  public: true
  plan:
  - get: repo
  - task: say-hello
    file: repo/tasks/task.yml
    params:
      VAULT_SECRET: ((vault-secret))
