---
platform: linux

image_resource:
  type: docker-image
#  source: {repository: rjain/buildbox}
  source: {repository: alpine}

params:
  VAULT_SECRET:

inputs:
  - name: repo

run:
  path: ./tasks/task.sh
